import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';

function Home ( { result, error } ) {
  if ( error ) {
    return <div className="h-screen flex justify-center items-center" ><p className="text-7xl text-red-900 m-auto">Error! { error }</p></div>;
  } else if ( !result ) {
    return <div>Loading...</div>;
  }
  const voci = result.voci.map( v => ( {
    id: v.id,
    nome: v.attributes.nome,
    descrizione: v.attributes.Descrizione,
    slug: v.attributes.slug,
    cover: v.attributes.cover.data?.attributes.url,
    categoria: v.attributes.categoria.data?.attributes.nome,
    caratteristiche: v.attributes.caratteristiche.data?.map( c => c.attributes ),
    allergeni: v.attributes.allergeni.data?.map( a => a.attributes ),
    prezzo: v.attributes.prezzo,

  } ) );
  const caratteristiche = result.caratteristiche.map( c => ( {
      id: c.id,
      nome: c.attributes.nome,
      slug: c.attributes.slug,
      icona: c.attributes.icona.data?.attributes.url,
  } ) );
  const allergeni = result.allergeni.map( a => ( {
      id: a.id,
      nome: a.attributes.nome,
      slug: a.attributes.slug,
      descrizione: a.attributes.descrizione,
      cover: a.attributes.cover.data?.attributes.url,
  } ) );
  const categorie = result.categorie.map( c => ( {
      id: c.id,
      nome: c.attributes.nome,
      slug: c.attributes.slug,
      descrizione: c.attributes.descrizione,
      cover: c.attributes.cover.data?.attributes.url,
  } ) );


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2 className='text-5xl font-bold text-red-800'>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
        <h2 className={styles.titolo}>Voci del menù</h2>
        <ul>
          {voci.map( v => (
            <li className="flex items-center justify-center" key={v.id}>
              <img className="h-4 mr-2" src={`http://localhost:1337${v.cover}`} alt={v.nome} />{v.nome}
            </li>
          ) )}
        </ul>
        <h2 className={styles.titolo}>Categorie</h2>
        <ul>
          {categorie.map( c => (
            <li className="flex items-center justify-center" key={c.id}>
              <img className="h-4 mr-2" src={`http://localhost:1337${c.cover}`} alt={c.nome} />{c.nome}
            </li>
          ) )}
        </ul>
        <h2 className={styles.titolo}>Allergeni</h2>
        <ul>
          {allergeni.map( a => (
            <li className="flex items-center justify-center" key={a.id}>
              {a.nome}
            </li>
          ) )}
        </ul>
        <h2 className={styles.titolo}>Caratteristiche</h2>
        <ul>
          {caratteristiche.map( c => (
            <li className="flex items-center justify-center" key={c.id}>
              <img className="h-4 mr-2" src={`http://localhost:1337${c.icona}`} alt={c.nome} />{c.nome}
            </li>
          ) )}
        </ul>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps () {
  try {
    const vociPromise = axios.get( 'http://localhost:1337/api/voci-del-menu?populate=*' );
    const caratteristichePromise = axios.get( 'http://localhost:1337/api/caratteristiche?populate=*' );
    const categoriePromise = axios.get( 'http://localhost:1337/api/categorie?populate=*' );
    const allergeniPromise = axios.get( 'http://localhost:1337/api/allergeni?populate=*' );
    const [ vociRaw, caratteristicheRaw, categorieRaw, allergeniRaw ] = await Promise
      .all( [ vociPromise, caratteristichePromise, categoriePromise, allergeniPromise ] );
    const voci = vociRaw.data.data;
    const caratteristiche = caratteristicheRaw.data.data;
    const categorie = categorieRaw.data.data;
    const allergeni = allergeniRaw.data.data;

    return {
      props: {
        result: {
          voci,
          caratteristiche,
          categorie,
          allergeni,
        },
        error: null
      },
    };
  } catch ( error ) {

    return {
      props: {
        result: null,
        error: error.message,
      },
    };
  }
}


  export default Home;